"""
T5 Interpretability Research — Probing Specifications

Pure data file. Contains:
- TraditionSpec dataclass for 15 musical traditions (Pillar 1)
- Pillar 2 material-physical vocabulary
- Structural controls (baselines, absurd, compositional, minimal pairs)

Design principle: SYMMETRICAL. No tradition is framed as "default" or "other".
All traditions get identical template structure, identical prompt counts.
"""

from dataclasses import dataclass, field
from typing import List


@dataclass
class TraditionSpec:
    """One musical tradition with its full vocabulary for template generation."""
    name: str                           # Canonical English label
    region_labels: List[str]            # Adjective forms for templates
    instruments: List[str]              # ~20 instruments
    vocal_styles: List[str]             # ~10 vocal styles
    spatial_contexts: List[str]         # ~10 performance spaces
    ensemble_contexts: List[str]        # ~10 ensemble types
    blind_descriptors: List[str]        # 50 acoustic descriptions WITHOUT naming the tradition


# ═══════════════════════════════════════════════════════════════════════════════
# PILLAR 1: 15 Musical Traditions
# ═══════════════════════════════════════════════════════════════════════════════

TRADITIONS: List[TraditionSpec] = [

    # ── 1. Ukrainian Folk Music ───────────────────────────────────────────────
    TraditionSpec(
        name="Ukrainian",
        region_labels=["Ukrainian", "Ukrainian folk", "Ukrainian traditional"],
        instruments=[
            "bandura", "kobza", "sopilka", "trembita", "tsymbaly",
            "lira (hurdy-gurdy)", "buben", "drymba", "surma", "buzok",
            "basolia", "skrypka", "bayan", "domra", "zhaleika",
            "rebro", "duda", "kuvytsi", "okaryna", "svystunets",
        ],
        vocal_styles=[
            "polyphonic choral singing", "solo lyrical singing", "recitative dumka",
            "wedding lament", "harvest song", "lullaby kolomyjka rhythm",
            "Cossack marching song", "ritual spring song", "call-and-response haymaking song",
            "melismatic ornamental singing",
        ],
        spatial_contexts=[
            "a village square", "a wooden church", "an open steppe",
            "a river bank at dusk", "a Carpathian mountain meadow",
            "a harvest festival field", "a wedding hall", "a forest clearing",
            "a market square", "a thatched farmhouse",
        ],
        ensemble_contexts=[
            "a troisti muzyky trio", "a bandura ensemble", "a folk choir",
            "a village wedding band", "a Cossack military ensemble",
            "a kobzar solo recital", "a caroling group", "a dance ensemble",
            "a church choir", "a festival orchestra",
        ],
        blind_descriptors=[
            "bright plucked strings with sympathetic resonance ringing",
            "deep drone under layered vocal harmonies",
            "nasal double-reed melody over drum pulse",
            "long sustained brass tone echoing across open terrain",
            "hammered dulcimer cascading in rapid arpeggios",
            "cranked continuous drone with melody wheel clicks",
            "frame drum with jingling rings accenting vocal rhythm",
            "jaw harp buzzing with overtone-rich twang",
            "high-pitched wooden flute with breathy attack",
            "deep chest voice in slow descending phrases",
            "women's voices in tight parallel thirds",
            "accordion bellows swell with ornamental runs",
            "round-bodied lute with gut strings plucked rapidly",
            "massed voices singing syllabic text in unison",
            "small reed pipe with sharp staccato articulation",
            "layered voices entering one by one in canon",
            "percussive foot stomping in complex meter",
            "high keening voice over sparse string accompaniment",
            "resonant bowed string with wide vibrato",
            "metal-stringed instrument tremolo under voice",
            "panpipe breathy chords in descending sequence",
            "solo voice with dramatic dynamic contrasts",
            "large button accordion in waltz rhythm",
            "plucked bass string punctuating vocal phrases",
            "cluster of small bells over rhythmic chanting",
            "overtone-rich bowed drone sustaining beneath melody",
            "rapid alternation between sung and spoken text",
            "wooden percussion keeping asymmetric dance beat",
            "two voices in tight dissonant seconds resolving",
            "low humming drone with high melody floating above",
            "bright metallic shimmer of struck wire strings",
            "solo wind instrument playing pentatonic phrases",
            "group singing with gradual accelerando",
            "plucked melody with rhythmic muting technique",
            "nasal singing voice with ornamental grace notes",
            "deep resonant bass voice singing sustained tones",
            "fast fiddle melody with open string drones",
            "rhythmic hand clapping in off-beat patterns",
            "gentle lullaby voice over soft string ostinato",
            "massive choral sound in reverberant stone space",
            "single-reed instrument playing ornamented slow melody",
            "strummed multi-string instrument in triple meter",
            "ceremonial horn blast followed by choral response",
            "high flute trill over low drone",
            "solo voice descending chromatically with vibrato",
            "layered plucked strings in harp-like texture",
            "driving dance rhythm with strong downbeats",
            "wailing vocal melody in minor mode",
            "rapid finger-picking producing melodic cascades",
            "sonorous male choir in deep register harmony",
        ],
    ),

    # ── 2. West African / Yoruba ──────────────────────────────────────────────
    TraditionSpec(
        name="Yoruba",
        region_labels=["Yoruba", "West African", "Yoruba traditional"],
        instruments=[
            "dundun (talking drum)", "bata drum", "shekere", "agogo bell",
            "gangan", "sakara drum", "agidigbo (thumb piano)", "aro drum",
            "sekere (gourd rattle)", "saworo (ankle bells)",
            "omele drum", "iya ilu (mother drum)", "gbedu drum",
            "awo drum", "konga", "igbin drum", "bembe drum",
            "wooden slit drum", "udú (clay pot drum)", "ere (flute)",
        ],
        vocal_styles=[
            "oriki praise chanting", "ijala hunting poetry",
            "rara group chanting", "solo ewi poetry recitation",
            "call-and-response work song", "orin Orisha devotional singing",
            "lullaby iremoje", "satirical song efufu",
            "masquerade ceremony vocals", "alamo choral singing",
        ],
        spatial_contexts=[
            "a palace courtyard", "an open-air market", "a sacred grove",
            "a village meeting ground", "a festival arena",
            "a riverbank shrine", "a masquerade procession route",
            "a communal gathering space", "a moonlit clearing",
            "an ancestor commemoration ground",
        ],
        ensemble_contexts=[
            "a dundun ensemble", "a bata drum orchestra",
            "an oriki praise troupe", "a ceremonial drum circle",
            "a wedding celebration ensemble", "a funeral procession group",
            "a masquerade performance troupe", "a hunters guild ensemble",
            "a naming ceremony group", "a festival drum corps",
        ],
        blind_descriptors=[
            "pitched drum mimicking speech contours with tonal inflection",
            "interlocking rhythms between three drums of different sizes",
            "gourd rattle creating steady sixteenth-note pulse",
            "iron bell cutting through dense polyrhythmic texture",
            "deep bass drum providing foundational pulse",
            "high-tension drum producing melodic speech patterns",
            "call from lead drum answered by chorus of smaller drums",
            "multiple rhythmic layers creating dense polymetric weave",
            "sharp wooden percussion accenting off-beats",
            "vocal chanting with drum mimicking the exact speech melody",
            "resonant clay pot producing deep hollow tone",
            "thumb piano plucking in repeating ostinato pattern",
            "ankle bells creating continuous metallic shimmer during movement",
            "rapid drum roll building tension before rhythmic break",
            "sustained vocal drone under rhythmic percussion",
            "high-pitched whistle melody interlocking with drums",
            "three distinct pitch levels in drum conversation",
            "group vocal response in rhythmic unison after solo call",
            "complex cross-rhythm between two time signatures simultaneously",
            "metal scraping on gourd surface in steady pattern",
            "deep booming drum hit followed by resonant sustain",
            "rapid hand-slap technique producing sharp crack on skin",
            "overlapping vocal parts creating continuous sound stream",
            "pitched percussion melody using graduated drum set",
            "staccato bell pattern against flowing vocal line",
            "ceremonial drum roll with increasing tempo and volume",
            "breathy wooden flute over polyrhythmic backdrop",
            "percussive body sounds mixed with vocal exclamations",
            "low humming chorus beneath solo declamation",
            "metallic jingle of seed-filled gourd in continuous shake",
            "bass drum heartbeat pulse underlying all other parts",
            "vocal ululation piercing through dense drum texture",
            "syncopated hand-clap pattern in compound meter",
            "drum pitch bending through arm-pressure technique",
            "dense rhythmic texture with no single dominant beat",
            "high nasal singing voice with rhythmic phrasing",
            "graduated drum pitches creating melodic contour",
            "sudden unison rhythmic break after complex passage",
            "sustained metallic ring from struck iron",
            "group chanting in accelerating tempo cycle",
            "layered percussion entering one by one building texture",
            "solo drum improvisation over steady ensemble groove",
            "hourglass-shaped drum gliding between pitches",
            "complex ratio of 3 against 4 in simultaneous parts",
            "vocal melody following tonal contour of language",
            "quiet scraping rhythm under explosive drum accents",
            "rhythmic breathing sounds integrated into percussion",
            "wooden claves setting timeline pattern",
            "thunderous ensemble climax with all instruments fortissimo",
            "gentle lullaby rhythm with soft drum and quiet singing",
        ],
    ),

    # ── 3. Indonesian / Gamelan ───────────────────────────────────────────────
    TraditionSpec(
        name="Gamelan",
        region_labels=["Indonesian", "Javanese gamelan", "Balinese gamelan"],
        instruments=[
            "saron (metallophone)", "bonang (gong chimes)", "gender (keyed metallophone)",
            "gambang (wooden xylophone)", "gong ageng (large gong)", "kempul (hanging gong)",
            "kenong (large kettle gong)", "ketuk (small kettle gong)", "suling (bamboo flute)",
            "rebab (bowed spike fiddle)", "kendang (drum)", "celempung (zither)",
            "slentem (low metallophone)", "peking (high metallophone)", "angklung",
            "calung (bamboo xylophone)", "reyong (gong row)", "ceng-ceng (cymbals)",
            "gentorak (bell tree)", "jegogan (large bamboo)",
        ],
        vocal_styles=[
            "sindhenan female solo singing", "gerong male chorus",
            "bawa solo unaccompanied opening", "senggakan vocal interjections",
            "dalang puppet master narration", "tembang macapat poetry singing",
            "kecak rhythmic chanting", "kidung devotional singing",
            "suluk mood-setting song", "ada-ada dramatic narration singing",
        ],
        spatial_contexts=[
            "an open-air pendopo pavilion", "a temple courtyard at night",
            "a palace audience hall", "a village ceremony ground",
            "a cremation tower procession", "a rice paddy terrace at dawn",
            "an inner palace chamber", "a shadow puppet stage",
            "a temple festival ground", "a rehearsal pavilion",
        ],
        ensemble_contexts=[
            "a full Javanese gamelan ensemble", "a Balinese gamelan gong kebyar",
            "a gender wayang quartet", "a gamelan sekaten ritual ensemble",
            "a gamelan degung ensemble", "an angklung orchestra",
            "a shadow puppet accompaniment ensemble", "a processional marching gamelan",
            "a gamelan selonding ensemble", "a bamboo gamelan jegog",
        ],
        blind_descriptors=[
            "shimmering metallic cascade in layered interlocking pattern",
            "deep resonant gong strike with long sustained decay",
            "rapid alternating metallophone patterns creating composite melody",
            "soft bamboo flute floating above dense metallic texture",
            "graduated gong chimes playing elaborating melody",
            "thick low bronze tone marking structural endpoint",
            "wooden xylophone adding dry staccato counterpoint",
            "bowed string instrument weaving between metallic layers",
            "small kettle gong marking regular time cycle",
            "massive ensemble suddenly dropping to near silence",
            "interlocking two-part pattern creating unified rapid melody",
            "resonant zither plucked in ornamental figurations",
            "male chorus singing in unison with metallic accompaniment",
            "high-pitched metallophone playing simplified core melody",
            "hanging gongs of different pitches punctuating cycle",
            "drum signaling tempo change with specific pattern",
            "bamboo tubes shaken producing warm pitched resonance",
            "cymbals crashing in rapid rhythmic accents",
            "soft female voice ornamenting between gong strokes",
            "colotomic structure with increasing density toward cadence",
            "pentatonic melody on bronze keys with damping technique",
            "sudden explosive tutti after gradual accelerando",
            "bell tree producing continuous high-frequency shimmer",
            "unison passage with all instruments on same melody",
            "low bamboo tubes producing deep resonant bass tones",
            "elaborate figuration on mid-range bronze keys",
            "vocal melody using pitch system outside Western tuning",
            "paired instruments alternating notes in kotekan pattern",
            "dramatic narrating voice over sparse accompaniment",
            "ceremonial opening with single gong strike into silence",
            "dense metallic texture with no clear single melody line",
            "gentle rippling metallophone beneath vocal ornaments",
            "accelerating tempo driven by drum signals",
            "two tuning systems creating acoustic beating effects",
            "processional rhythm with marching regularity",
            "high metallic shimmer fading into deep gong resonance",
            "rapid tremolo on keyed instrument creating sustained tone",
            "rhythmic vocal chanting building in intensity",
            "melodic elaboration becoming increasingly complex",
            "sudden dynamic shift from fortissimo to pianissimo",
            "bronze resonance lingering after final stroke",
            "staccato damped notes alternating with ringing tones",
            "cross-rhythmic pattern between drums and metallophones",
            "ethereal flute melody in free rhythm over steady pulse",
            "gradually layering instruments entering one by one",
            "composite melody emerging from interlocked individual parts",
            "warm bronze timbre with slight detuning creating shimmer",
            "circular melodic pattern repeating with variations",
            "massive final gong stroke ending cyclic structure",
            "quiet contemplative passage with sparse instrumentation",
        ],
    ),

    # ── 4. Classical Arabic ───────────────────────────────────────────────────
    TraditionSpec(
        name="Arabic",
        region_labels=["Arabic", "classical Arabic", "Arab traditional"],
        instruments=[
            "oud", "qanun (zither)", "ney (end-blown flute)", "riq (tambourine)",
            "tabla (goblet drum)", "rabab (bowed fiddle)", "buzuq",
            "mijwiz (double-pipe)", "arghul (double clarinet)", "sagat (finger cymbals)",
            "darbuka", "bendir (frame drum)", "kamanjah (violin)",
            "santir (hammered dulcimer)", "zurna (oboe)", "shababa (flute)",
            "tabl baladi (bass drum)", "mazhar (large frame drum)",
            "jawzah (spike fiddle)", "oud bass",
        ],
        vocal_styles=[
            "maqam-based improvised taqasim singing", "muwashshah metric poetry singing",
            "Quranic recitation tajwid", "layali vocal improvisation",
            "mawwal narrative ballad singing", "zajal vernacular poetry singing",
            "nasheed devotional chanting", "ataba lament singing",
            "tarab ecstatic lyrical singing", "group inshad choral singing",
        ],
        spatial_contexts=[
            "a palace courtyard with fountain", "a desert tent gathering",
            "a mosque interior", "an old city coffee house",
            "a seaside promenade", "an oasis garden",
            "a rooftop terrace at night", "a grand concert hall",
            "a covered bazaar", "a mountain village square",
        ],
        ensemble_contexts=[
            "a takht ensemble", "a firqah orchestra", "a solo oud recital",
            "a Sufi dhikr circle", "a wedding band with singer",
            "a maqam study group", "a military brass and drum ensemble",
            "a vocal and oud duo", "a qanun and ney duet",
            "a full tarab orchestra",
        ],
        blind_descriptors=[
            "rounded plucked lute with warm deep resonance",
            "plucked zither cascading in rapid ornamental runs",
            "breathy end-blown flute with microtonal inflections",
            "tambourine with complex finger-roll technique",
            "goblet drum producing crisp high and deep low strokes",
            "bowed string playing long ornamental melodic phrases",
            "vocal improvisation exploring microtonal pitch space",
            "metric vocal melody over plucked accompaniment",
            "double-pipe drone with melody above",
            "finger cymbals marking rhythmic accents delicately",
            "melismatic vocal ornament spanning wide pitch range",
            "plucked instrument tremolo sustaining lyrical melody",
            "nasal oboe melody soaring over drum pattern",
            "solo voice in free rhythm building emotional intensity",
            "hammered dulcimer producing shimmering repeated tones",
            "group chanting in rhythmic unison with percussion",
            "quarter-tone inflection bending pitch expressively",
            "call from solo voice answered by instrumental refrain",
            "deep frame drum boom with overtone resonance",
            "rapid plucked ornamentation between held vocal notes",
            "long sustained flute note with gradual dynamic swell",
            "complex asymmetric rhythm cycle in percussion",
            "violin playing in ornamental style with quarter-tones",
            "vocal sigh descending through microtonal intervals",
            "strummed chord punctuating between vocal phrases",
            "ecstatic vocal climax with audience response",
            "gentle lute arpeggio beneath spoken poetry",
            "drum solo showcasing rapid finger techniques",
            "ensemble heterophony on shared melodic contour",
            "quiet contemplative flute solo in empty space",
            "dense ensemble texture building toward rhythmic cadence",
            "bass drone string sustaining under melodic elaboration",
            "rhythmic hand-clap pattern in compound meter",
            "vocal trill on sustained pitch with vibrato",
            "ascending melodic phrase building tension gradually",
            "sudden silence before dramatic vocal entry",
            "plucked string harmonics ringing like bells",
            "group response singing in tight rhythmic unison",
            "slow rubato melody over sparse accompaniment",
            "metallic jingle of tambourine in continuous pattern",
            "modulating between related melodic modes mid-phrase",
            "low humming drone beneath high ornamental melody",
            "rhythmic breathing integrated into vocal technique",
            "rapid descending scale on plucked instrument",
            "duet between flute and voice in parallel motion",
            "percussive slap on drum body creating dry accent",
            "echo effect in resonant architectural space",
            "gradual accelerando building collective energy",
            "solo instrumental meditation in free tempo",
            "massive unison orchestral statement with full force",
        ],
    ),

    # ── 5. Jewish Traditional + Modern ────────────────────────────────────────
    TraditionSpec(
        name="Jewish",
        region_labels=["Jewish", "Jewish traditional", "Jewish liturgical"],
        instruments=[
            "shofar (ram's horn)", "kinnor (lyre)", "tof (frame drum)",
            "nevel (harp)", "clarinet", "violin (klezmer)",
            "tsimbl (hammered dulcimer)", "accordion", "double bass",
            "flute", "trumpet", "drum kit",
            "guitar", "mandolin", "piano",
            "synthesizer", "oud (Mizrahi)", "darbuka (Mizrahi)",
            "tambourine", "organ",
        ],
        vocal_styles=[
            "cantorial chanting hazzan", "niggun wordless melody",
            "Yiddish folk song singing", "psalm recitation",
            "piyyut liturgical poetry", "zmiroth table songs",
            "Ladino romance singing", "Mizrahi piyyut singing",
            "hasidic ecstatic singing", "Israeli art song singing",
        ],
        spatial_contexts=[
            "a synagogue sanctuary", "a Shabbat dinner table",
            "a wedding canopy outdoors", "a klezmer dance hall",
            "a yeshiva study hall", "a Hasidic gathering room",
            "a memorial ceremony space", "a kibbutz dining hall",
            "a concert hall stage", "a hillside amphitheater",
        ],
        ensemble_contexts=[
            "a klezmer band", "a synagogue choir", "a Hasidic circle dance group",
            "a cantorial ensemble", "a Mizrahi wedding orchestra",
            "a Ladino vocal ensemble", "a Israeli chamber group",
            "a folk song duo", "a liturgical organ and choir",
            "a niggun singing circle",
        ],
        blind_descriptors=[
            "raw animal horn blast with rich overtone spectrum",
            "clarinet wailing in augmented second intervals",
            "violin playing ornamental crying melody",
            "wordless humming melody building in collective intensity",
            "hammered dulcimer sparkling over dance rhythm",
            "accordion pumping in alternating bass and chord",
            "deep bass string driving dance groove",
            "solo cantor voice with elaborate melismatic ornamentation",
            "group singing simple repetitive melody with increasing fervor",
            "frame drum keeping steady celebratory rhythm",
            "high clarinet trill cascading into low register",
            "minor key melody with augmented second interval",
            "flute playing pastoral melody over sparse accompaniment",
            "piano chords supporting lyrical vocal melody",
            "trumpet fanfare with celebratory character",
            "solo voice in free rhythm with emotional vibrato",
            "call-and-response between cantor and congregation",
            "plucked string accompaniment in waltz-like meter",
            "organ sustaining chords beneath choral singing",
            "synthesizer drone under acoustic instruments",
            "rapid violin passage in dance tempo",
            "mandolin tremolo sustaining melody note",
            "goblet drum adding Middle Eastern rhythmic pattern",
            "rounded lute providing harmonic foundation",
            "group stamping feet in rhythmic dance pattern",
            "descending melodic sigh expressing lament",
            "celebratory shout punctuating between musical phrases",
            "gentle lullaby with rocking rhythmic pattern",
            "chromatic ornamental runs on wind instrument",
            "bass and drums locking into klezmer groove",
            "solo instrumental meditation in slow free tempo",
            "modal melody shifting between major and minor",
            "collective ecstatic singing reaching peak intensity",
            "whispered chanting building to full voice",
            "staccato rhythmic accompaniment under flowing melody",
            "wide vibrato on bowed string creating emotional tension",
            "antiphonal singing between two groups",
            "tambourine adding jingle to festive rhythm",
            "sustained chord resolution after chromatic tension",
            "improvised vocal ornamentation on held syllable",
            "dance rhythm alternating between duple and triple feel",
            "muted trumpet playing tender lyrical melody",
            "guitar strumming in Ladino ballad style",
            "hushed solo voice in reverberant sacred space",
            "driving accelerando in celebratory dance",
            "ornamental grace notes cascading on clarinet",
            "layered voices in parallel harmony movement",
            "percussive hand-clap syncopation in dance circle",
            "plaintive melody descending to low register resolution",
            "full ensemble unison statement with rhythmic precision",
        ],
    ),

    # ── 6. Franconian / Middle Franconian ─────────────────────────────────────
    TraditionSpec(
        name="Franconian",
        region_labels=["Franconian", "Middle Franconian", "Franconian folk"],
        instruments=[
            "Schalmei (shawm)", "Drehleier (hurdy-gurdy)", "Hackbrett (hammered dulcimer)",
            "Zither", "Steirische Harmonika (button accordion)", "fiddle",
            "Flügelhorn", "clarinet", "tuba", "trombone",
            "Schwegel (fife)", "Dudelsack (bagpipe)", "guitar",
            "Kontrabass (double bass)", "Waldhorn (French horn)", "snare drum",
            "cymbals", "trumpet", "Blockflöte (recorder)", "Mundharmonika (harmonica)",
        ],
        vocal_styles=[
            "Franconian dialect folk singing", "Kirchweih (church fair) singing",
            "yodeling variations", "Wirtshausgesang (tavern singing)",
            "choral singing in four-part harmony", "Schnaderhüpfel (rhyming verse)",
            "children's counting rhyme singing", "harvest festival singing",
            "Passion play narration singing", "Christmas carol singing",
        ],
        spatial_contexts=[
            "a village beer garden", "a church square during Kirchweih",
            "a half-timbered tavern hall", "a vineyard hillside",
            "a town market square", "a forest meadow",
            "a Baroque church interior", "a castle courtyard",
            "a riverside promenade", "a festival tent",
        ],
        ensemble_contexts=[
            "a Blaskapelle brass band", "a Stubenmusik chamber group",
            "a Kirchweih dance band", "a folk choir",
            "a Schuhplattler dance ensemble", "a brass quintet",
            "a Wirtshausmusik tavern trio", "a processional marching band",
            "a village dance orchestra", "a folk music school ensemble",
        ],
        blind_descriptors=[
            "brass ensemble playing in warm rounded tone",
            "button accordion bellows swell with ornamental runs",
            "hammered dulcimer sparkling arpeggios in triple meter",
            "zither plucked melody over drone strings",
            "deep tuba providing steady oom-pah bass pattern",
            "shawm playing bright nasal melody",
            "hurdy-gurdy drone with cranked melody wheel",
            "fife playing high-pitched dance tune",
            "bagpipe drone with chanter melody above",
            "fiddle playing in Ländler dance rhythm",
            "trombone glissando in humorous tavern music",
            "clarinet playing lyrical slow waltz melody",
            "French horn call echoing in natural setting",
            "double bass plucking steady quarter-note pulse",
            "snare drum roll leading into brass fanfare",
            "recorder playing simple folk melody",
            "harmonica bending notes in folk tune",
            "four-part male choir singing in thirds",
            "guitar strumming waltz accompaniment pattern",
            "trumpet playing bright processional melody",
            "group singing dialect verses with rhythmic stomping",
            "accordion and fiddle duet in fast polka",
            "gentle lullaby with soft string accompaniment",
            "brassy fortissimo in festive march tempo",
            "yodel alternating between chest and head voice",
            "cymbal crash accenting downbeat in march",
            "solo clarinet playing rubato pastoral melody",
            "full brass band in ceremonial fanfare",
            "tavern singing with table-slapping rhythm",
            "gentle waltz melody on hammered dulcimer",
            "bagpipe and drum in processional rhythm",
            "children's voices singing simple repetitive tune",
            "accordion solo with bass register melody",
            "brass choir in reverent hymn-like setting",
            "rapid polka tempo with driving dance beat",
            "solo voice singing verses with choral refrain",
            "deep brass sustain resolving to major chord",
            "fiddle ornaments in fast dance passage",
            "marching band approaching from distance growing louder",
            "soft evening serenade with gentle guitar and voice",
            "festive crowd singing along with brass band",
            "tuba and bass drum providing heavy dance groove",
            "flügelhorn playing lyrical melody with warm tone",
            "rhythmic foot-stomping in synchronized dance",
            "hurdy-gurdy playing drone-based dance tune",
            "choir singing in reverberant church acoustic",
            "accordion tremolo sustaining sentimental melody",
            "alternating solo verses with full ensemble chorus",
            "quiet recorder melody in pastoral setting",
            "massive brass fortissimo ending with cymbal crash",
        ],
    ),

    # ── 7. African American ───────────────────────────────────────────────────
    TraditionSpec(
        name="African American",
        region_labels=["African American", "Black American", "African American traditional"],
        instruments=[
            "electric guitar", "acoustic guitar", "piano", "Hammond organ",
            "upright bass", "electric bass", "drum kit", "banjo",
            "harmonica", "saxophone (alto)", "saxophone (tenor)",
            "trumpet", "trombone", "fiddle", "washboard",
            "tambourine", "congas", "turntable", "sampler",
            "drum machine",
        ],
        vocal_styles=[
            "blues shouting", "gospel melismatic singing", "scat improvisation",
            "field holler", "call-and-response preaching", "doo-wop harmony",
            "rap rhythmic speech", "soul belting", "spoken word poetry",
            "ring shout chanting",
        ],
        spatial_contexts=[
            "a juke joint", "a gospel church", "a jazz club stage",
            "a front porch", "a street corner", "a concert hall",
            "a recording studio", "a community center", "a barbershop",
            "an outdoor festival stage",
        ],
        ensemble_contexts=[
            "a blues trio", "a gospel choir with organ", "a jazz quartet",
            "a big band", "a string band", "a funk rhythm section",
            "a hip-hop production setup", "a doo-wop vocal group",
            "a brass band second line", "a solo singer-guitarist",
        ],
        blind_descriptors=[
            "bent guitar note with overdriven amplifier sustain",
            "walking bass line in steady quarter-note swing",
            "piano playing boogie-woogie left-hand pattern",
            "organ sustaining chords with rotating speaker tremolo",
            "drum kit shuffle pattern with hi-hat swing",
            "harmonica bending blue notes expressively",
            "saxophone solo with breathy tone and wide vibrato",
            "trumpet playing muted intimate melody",
            "trombone growling in low register",
            "solo voice with intense emotional vibrato",
            "banjo playing rapid fingerpicking pattern",
            "washboard scraped in rhythmic pattern",
            "call from solo voice answered by massed choir",
            "group singing tight harmony in close voicing",
            "rhythmic spoken delivery over beat pattern",
            "bass and drums locking into deep groove",
            "piano comping syncopated chords behind soloist",
            "guitar slide technique producing vocal-like portamento",
            "tambourine shaking on backbeat accents",
            "turntable scratching adding rhythmic texture",
            "improvised saxophone run over chord changes",
            "gospel organ building intensity with tremolo",
            "choir clapping on beats two and four",
            "electric bass playing funk slap technique",
            "drum machine providing steady electronic pulse",
            "solo voice rising to climactic high note",
            "twelve-bar harmonic pattern repeating cyclically",
            "massed voices swelling in spiritual ecstasy",
            "guitar feedback sustaining into next phrase",
            "brush drums playing soft ballad accompaniment",
            "brass section playing tight rhythmic punches",
            "piano tremolo building emotional intensity",
            "deep bass voice singing steady bottom notes",
            "fast bebop melody with chromatic alterations",
            "spoken word flowing rhythmically over ambient sound",
            "layered vocal samples creating texture",
            "fingerpicked acoustic guitar in bottleneck style",
            "congas adding polyrhythmic layer to groove",
            "organ pedal bass sustaining beneath choir",
            "electric guitar wah-wah effect in funk rhythm",
            "collective improvisation with overlapping solos",
            "unaccompanied voice singing in rubato",
            "drum break with syncopated snare fills",
            "horn section playing melodic riff in unison",
            "quiet hum building into powerful choral climax",
            "piano playing rolling gospel figure",
            "saxophone honking repeated notes with urgency",
            "bass string pulled and released creating snap",
            "vocal melisma spanning two octaves",
            "rhythmic hand-clap pattern driving song momentum",
        ],
    ),

    # ── 8. Romani / Sinti ─────────────────────────────────────────────────────
    TraditionSpec(
        name="Romani",
        region_labels=["Romani", "Sinti", "Romani traditional"],
        instruments=[
            "violin", "cimbalom (hammered dulcimer)", "double bass",
            "acoustic guitar", "clarinet", "accordion",
            "tambourine", "darbuka", "trumpet", "trombone",
            "flute", "viola", "saxophone", "mandolin",
            "bass guitar", "drum kit", "spoons", "zurna",
            "tapan (large drum)", "gadulka (bowed string)",
        ],
        vocal_styles=[
            "passionate solo singing with wide vibrato",
            "group singing in close harmony",
            "melismatic wailing lament",
            "rhythmic vocal improvisation",
            "call-and-response party singing",
            "children's song singing",
            "narrative ballad singing",
            "ecstatic celebratory singing",
            "lullaby singing with ornamental grace notes",
            "spoken-sung rhythmic storytelling",
        ],
        spatial_contexts=[
            "a wedding celebration hall", "a campfire gathering",
            "a cafe terrace", "a town square festival",
            "a family courtyard", "a theater stage",
            "a train station platform", "a market stall area",
            "a river bank settlement", "a dance floor",
        ],
        ensemble_contexts=[
            "a wedding ensemble", "a cafe band", "a family music group",
            "a brass band", "a string ensemble", "a dance accompaniment group",
            "a solo vocalist with guitar", "a cimbalom and violin duo",
            "a festival orchestra", "a street musician troupe",
        ],
        blind_descriptors=[
            "violin playing virtuosic ornamental passage at high speed",
            "hammered dulcimer tremolo sparkling over bass pulse",
            "double bass plucking driving dance rhythm",
            "guitar strumming rapid rhythmic accompaniment",
            "clarinet playing sinuous chromatic melody",
            "accordion pumping in fast dance tempo",
            "tambourine jingling in continuous rhythmic shaking",
            "passionate voice with wide ornamental vibrato",
            "trumpet playing bright melody with emotional intensity",
            "group voices singing in tight thirds and sixths",
            "violin and clarinet playing parallel ornamental melody",
            "rapid tempo acceleration building dance frenzy",
            "low bass drone under virtuosic melodic fireworks",
            "drum providing heavy downbeat in asymmetric meter",
            "flute playing lyrical slow melody with ornaments",
            "spoons clicking in rapid rhythmic pattern",
            "voice wailing in descending minor scale lament",
            "full ensemble playing in rhythmic unison break",
            "solo violin improvisation with double stops",
            "guitar fingerpicking in Spanish-influenced style",
            "brass section blasting festive fanfare",
            "cimbalom playing melodic cascade in rapid arpeggios",
            "deep male voice singing narrative verses",
            "high female voice with piercing emotional quality",
            "sudden rhythmic stop followed by solo vocal cadenza",
            "saxophone adding jazzy color to acoustic ensemble",
            "viola playing inner voice countermelody",
            "mandolin tremolo sustaining romantic melody",
            "complex meter switching between 7/8 and 4/4",
            "percussive guitar body slapping adding rhythm",
            "ecstatic vocal climax with audience clapping along",
            "gentle lullaby with soft guitar arpeggios",
            "virtuosic violin playing in extreme high register",
            "bass and guitar locked in driving groove",
            "clarinet bending notes with vocal-like expression",
            "collective accelerando reaching breathtaking speed",
            "quiet contemplative violin solo in minor mode",
            "festive brass and drum processional march",
            "melodic ornamentation using augmented seconds",
            "rapid finger technique on dulcimer creating blur",
            "solo voice holding long sustained note with vibrato",
            "ensemble building from silence to maximum volume",
            "dance rhythm with strong accent pattern",
            "chromatic melodic runs connecting phrase sections",
            "emotional singing with audible tears in voice",
            "rhythmic foot-stomping synchronized with music",
            "accordion bellows shake creating tremolo effect",
            "multiple string instruments in heterophonic texture",
            "sudden key change elevating emotional intensity",
            "massive ensemble finale with all instruments fortissimo",
        ],
    ),

    # ── 9. Japanese ───────────────────────────────────────────────────────────
    TraditionSpec(
        name="Japanese",
        region_labels=["Japanese", "Japanese traditional", "Japanese classical"],
        instruments=[
            "shakuhachi (bamboo flute)", "shamisen (three-string lute)",
            "koto (zither)", "biwa (lute)", "taiko (drum)",
            "tsuzumi (hourglass drum)", "noh flute (nohkan)",
            "shō (mouth organ)", "hichiriki (double-reed pipe)",
            "ryūteki (transverse flute)", "kakko (small drum)",
            "mokugyo (wooden fish)", "suzu (bell tree)", "kane (gong)",
            "fue (general flute)", "sanshin (Okinawan lute)",
            "kokyū (bowed fiddle)", "wadaiko (large drum)",
            "shime-daiko (small tied drum)", "chappa (small cymbals)",
        ],
        vocal_styles=[
            "noh drama chanting utai", "kabuki vocal stylization",
            "min'yō folk singing", "enka emotional ballad singing",
            "shōmyō Buddhist chanting", "rōkyoku narrative singing",
            "jiuta-mai dance singing", "nagauta long song singing",
            "Ainu upopo group singing", "gagaku vocal hymn singing",
        ],
        spatial_contexts=[
            "a noh theater stage", "a Zen temple garden",
            "a tatami room", "a shrine festival ground",
            "a bamboo grove", "a mountain temple at dawn",
            "a kabuki theater", "a tea ceremony room",
            "a seaside at twilight", "a castle courtyard",
        ],
        ensemble_contexts=[
            "a gagaku court music ensemble", "a noh hayashi percussion group",
            "a koto and shakuhachi duo", "a shamisen and voice duo",
            "a taiko drumming ensemble", "a kabuki music ensemble",
            "a sankyoku trio", "a min'yō folk ensemble",
            "a shōmyō Buddhist choir", "a festival hayashi ensemble",
        ],
        blind_descriptors=[
            "breathy bamboo flute with silence between phrases",
            "plucked three-string lute with percussive snap",
            "long zither glissando across silk strings",
            "deep drum strike with resonant body tone",
            "piercing high-pitched flute cutting through silence",
            "mouth organ producing sustained cluster chord",
            "nasal double-reed playing sustained ornamental melody",
            "small hourglass drum producing sharp crack",
            "wooden fish percussion keeping steady pulse",
            "large drum thundering with full body force",
            "bell tree producing delicate high shimmer",
            "solo flute playing in ma-filled phrasing with long pauses",
            "plucked string with deliberate finger noise as expression",
            "bowed lute producing raspy sustained tone",
            "transverse flute playing flowing court melody",
            "chanting voice with extreme slow tempo and ornamentation",
            "explosive drum hit followed by extended silence",
            "gong strike ringing with long overtone decay",
            "vocal narration stylized with dramatic pitch contour",
            "group drumming building from slow to explosive climax",
            "three instruments playing in heterophonic texture",
            "plucked bass string with buzzing bridge resonance",
            "high whistle tone on bamboo flute at extreme range",
            "slow contemplative melody with microtonal bending",
            "small cymbals providing metallic rhythmic accent",
            "Okinawan lute with bright twangy tone",
            "Buddhist chant in deep unison with bell punctuation",
            "rhythmic stomping feet on wooden stage floor",
            "alternating between sound and deliberate silence",
            "kabuki dramatic vocal cry with sliding pitch",
            "folk singing voice with natural untrained quality",
            "emotional ballad voice with heavy vibrato",
            "court ensemble in slow stately tempo",
            "festival percussion creating energetic driving rhythm",
            "solo bowed string in melancholic free rhythm",
            "narrative singing with shamisen punctuation between phrases",
            "massive taiko ensemble building wall of rhythmic sound",
            "quiet tea ceremony ambiance with minimal sound",
            "dance music with rhythmic vocal calls",
            "gradual pitch bend on sustained wind instrument tone",
            "sparse texture with each note given individual weight",
            "vocal ornament using microtonal grace notes",
            "drum rhythm accelerating toward dramatic climax",
            "pentatonic melody on plucked string instrument",
            "breath noise as intentional musical element",
            "ceremonial procession music with steady walking tempo",
            "solo instrument playing in vast acoustic space",
            "sharp percussive accent followed by resonant decay",
            "ensemble decelerating into stillness",
            "single sustained tone gradually fading to nothing",
        ],
    ),

    # ── 10. Korean / Pansori ──────────────────────────────────────────────────
    TraditionSpec(
        name="Korean",
        region_labels=["Korean", "Korean traditional", "Korean classical"],
        instruments=[
            "gayageum (zither)", "geomungo (zither)", "haegeum (bowed fiddle)",
            "daegeum (transverse flute)", "piri (double-reed pipe)",
            "janggu (hourglass drum)", "buk (barrel drum)", "kkwaenggwari (small gong)",
            "jing (large gong)", "sogeum (small flute)",
            "ajaeng (bowed zither)", "yanggeum (hammered dulcimer)",
            "saenghwang (mouth organ)", "taepyeongso (shawm)",
            "pyeongyeong (stone chimes)", "pyeonjong (bronze bell set)",
            "nagak (conch shell horn)", "bara (cymbals)",
            "dangbipa (lute)", "komungo (six-string zither)",
        ],
        vocal_styles=[
            "pansori epic narrative singing", "minyo folk singing",
            "kagok classical lyric singing", "sijo poetry singing",
            "nongak farmers band chanting", "Buddhist beompae chanting",
            "gut shamanic ritual singing", "changga modern art singing",
            "arirang regional folk singing", "punmul rhythmic vocal calls",
        ],
        spatial_contexts=[
            "a palace courtyard", "a village rice paddy field",
            "a Buddhist temple hall", "a mountain pavilion",
            "a folk festival arena", "a pansori performance stage",
            "a Confucian shrine", "a marketplace",
            "a riverside park", "a traditional house courtyard",
        ],
        ensemble_contexts=[
            "a samulnori percussion quartet", "a court music ensemble (aak)",
            "a pansori singer with drum accompaniment", "a sanjo solo with janggu",
            "a sinawi improvisation ensemble", "a nongak farmers band",
            "a gayageum ensemble", "a wind and string orchestra",
            "a Buddhist ceremony ensemble", "a folk dance music group",
        ],
        blind_descriptors=[
            "twelve-string zither plucked with deep resonant twang",
            "bowed fiddle playing sinuous ornamental melody",
            "transverse bamboo flute with wide vibrato and overblowing",
            "double-reed pipe sustaining intense nasal melody",
            "hourglass drum creating complex rhythmic pattern with two sticks",
            "barrel drum providing deep resonant steady pulse",
            "small gong cutting through with bright metallic strike",
            "large gong booming with long sustaining wash",
            "bowed bass zither producing rough growling tone",
            "hammered dulcimer cascading in bright arpeggios",
            "solo voice in dramatic narrative with extreme vocal range",
            "voice breaking into raspy timbre at emotional climax",
            "rhythmic vocal shouts driving percussion ensemble",
            "gentle plucked melody with sliding pitch ornaments",
            "conch shell horn producing deep ceremonial blast",
            "stone chimes producing clear pitched ringing tones",
            "bronze bells struck in melodic sequence",
            "mouth organ sustaining cluster of pitches",
            "shawm playing piercing outdoor ceremonial melody",
            "group percussion in interlocking rhythmic patterns",
            "solo singer varying between soft whisper and powerful shout",
            "drum accompanist responding to singer's emotional cues",
            "zither tremolo creating sustained vibrating tone",
            "flute and voice trading melodic phrases",
            "cymbal crash marking structural moment in cycle",
            "folk singing voice with natural regional dialect quality",
            "four percussion instruments creating complex composite rhythm",
            "slow courtly melody with extreme ornamental detail",
            "shamanic vocal style with guttural extended technique",
            "accelerating rhythmic cycle building to climax",
            "plucked string harmonics ringing bell-like",
            "bowed string glissando sliding through pitch space",
            "nasal singing voice with characteristic Korean vibrato",
            "drum pattern shifting between different rhythmic cycles",
            "gentle Buddhist chanting with bell and wooden percussion",
            "explosive percussion break after building tension",
            "solo instrument playing in pentatonic mode",
            "emotional vocal sigh descending with heavy vibrato",
            "ensemble heterophony each instrument ornamenting differently",
            "cymbals and gong creating metallic wash of sound",
            "narrative singing alternating with dramatic spoken sections",
            "rhythmic breathing sounds as musical element",
            "rapid plucked passage showcasing virtuosic technique",
            "deep sustained drone beneath melodic activity",
            "group singing folk melody in natural unison",
            "improvised instrumental passage over steady drum rhythm",
            "ceremonial procession music with stately tempo",
            "sudden dynamic contrast from loud to whisper-quiet",
            "multiple rhythmic layers creating dense polymetric texture",
            "final sustained gong tone fading into silence",
        ],
    ),

    # ── 11. Hindustani Classical ──────────────────────────────────────────────
    TraditionSpec(
        name="Hindustani",
        region_labels=["Hindustani", "North Indian classical", "Hindustani classical"],
        instruments=[
            "sitar", "tabla", "sarod", "tanpura",
            "bansuri (bamboo flute)", "shehnai (double-reed pipe)", "sarangi (bowed fiddle)",
            "santoor (hammered dulcimer)", "surbahar (bass sitar)", "harmonium",
            "pakhawaj (barrel drum)", "violin (Hindustani style)", "dilruba (bowed sitar)",
            "vichitra veena (slide instrument)", "esraj (bowed string)",
            "swarmandal (auto-harp zither)", "jaltarang (water-tuned bowls)",
            "nagara (kettledrum)", "dholak (two-headed drum)", "manjira (small cymbals)",
        ],
        vocal_styles=[
            "dhrupad alap improvisation", "khayal vilambit slow composition",
            "thumri light classical singing", "bhajan devotional singing",
            "ghazal lyric poetry singing", "qawwali ecstatic devotional singing",
            "tarana rhythmic syllable singing", "tappa ornamental singing",
            "sargam sol-fa passage singing", "hori seasonal festival singing",
        ],
        spatial_contexts=[
            "a baithak intimate concert room", "a temple sanctum",
            "a palace durbar hall", "an open-air mehfil gathering",
            "a shrine courtyard", "a recording studio",
            "a concert hall stage", "a riverbank at dawn",
            "a rooftop terrace at night", "a festival tent",
        ],
        ensemble_contexts=[
            "a sitar and tabla duo", "a sarod and tanpura duo",
            "a vocal recital with harmonium and tabla", "a shehnai and nagara duo",
            "a sarangi and tabla accompaniment", "a qawwali ensemble",
            "a santoor and tabla duo", "a jugalbandi duet",
            "a dhrupad ensemble with pakhawaj", "a light classical group",
        ],
        blind_descriptors=[
            "resonant plucked string with long sustaining sympathetic buzz",
            "hand drums producing crisp syllabic rhythmic patterns",
            "deep metallic pluck with sliding portamento between notes",
            "four-string drone instrument humming continuous pitch",
            "breathy bamboo flute playing slow ascending phrases",
            "nasal double-reed sustained in continuous circular breath",
            "bowed string instrument with intense vocal-like quality",
            "hammered dulcimer cascading in rapid melodic patterns",
            "deep bass plucked string with powerful resonance",
            "bellows organ sustaining chords beneath vocalist",
            "barrel drum producing deep resonant strokes",
            "violin playing ornamental meend slides",
            "bowed sitar-like instrument creating sustained singing tone",
            "slide instrument gliding through continuous pitch spectrum",
            "zither strings swept before main vocal entry",
            "water-tuned ceramic bowls struck melodically",
            "kettledrum providing ceremonial rhythmic foundation",
            "small cymbals marking rhythmic accents in devotional music",
            "voice slowly exploring ascending melodic contour note by note",
            "gradual acceleration from very slow to extremely fast tempo",
            "tabla dialogue between bass and treble drum heads",
            "continuous drone establishing tonal center throughout",
            "melodic phrase descending through ornamental curves",
            "vocal improvisation with extreme melismatic ornamentation",
            "rhythmic composition with complex mathematical structure",
            "climactic fast passage after long slow development",
            "musician and drummer trading improvised rhythmic ideas",
            "subtle microtonal inflection bending pitch expressively",
            "ecstatic group singing building collective intensity",
            "rhythmic syllables sung at increasing speed",
            "morning raga melody evoking dawn atmosphere",
            "evening raga with contemplative descending phrases",
            "plucked instrument playing rapid tihai rhythmic cadence",
            "bowed string imitating vocal ornamental technique",
            "slow meditative alap without rhythmic accompaniment",
            "sudden rhythmic entry after extended free introduction",
            "ornamental turn around single melodic pitch",
            "descending glissando on plucked string covering wide range",
            "call-and-response between melody and drum",
            "devotional singing with emotional audience participation",
            "tanpura drone creating rich overtone halo",
            "fast rhythmic passage with precise mathematical groupings",
            "vocal taan running rapidly through scale patterns",
            "light playful melody with romantic emotional quality",
            "sustained high note with gradual vibrato intensification",
            "complex tabla solo with spoken rhythmic composition",
            "melodic instrument and voice in unison ornamentation",
            "gentle strumming establishing rhythmic cycle",
            "intense emotional climax with maximum speed and volume",
            "final sustained tonic note resolving all tension",
        ],
    ),

    # ── 12. Tuvan Throat Singing / Khoomei ────────────────────────────────────
    TraditionSpec(
        name="Tuvan",
        region_labels=["Tuvan", "Tuvan throat singing", "Tuvan traditional"],
        instruments=[
            "igil (two-string bowed fiddle)", "doshpuluur (three-string plucked lute)",
            "chanzy (three-string plucked lute)", "chadagan (zither)",
            "khomus (jaw harp)", "limbi (transverse flute)",
            "murgu (birch bark horn)", "shoor (end-blown flute)",
            "bayan (button accordion)", "dungur (frame drum)",
            "demir-khomus (metal jaw harp)", "byzaanchy (four-string bowed fiddle)",
            "amyrga (hunting horn)", "ediski (reed pipe)", "shang (small bells)",
            "kengirge (frame drum with handle)", "kuzungu (mirror rattle)",
            "dopshuluur (two-string lute variant)", "tumruk (rattle)", "kubyz (wooden jaw harp)",
        ],
        vocal_styles=[
            "khoomei fundamental throat singing", "sygyt whistling overtone singing",
            "kargyraa deep undertone singing", "borbangnadyr rolling throat singing",
            "ezengileer stirrup-rattling overtone singing", "dumchuktaar nasal throat singing",
            "dag kargyraazy mountain kargyraa variant", "oidupaa nature mimicry singing",
            "kozhamyk humorous song singing", "folk long-song singing",
        ],
        spatial_contexts=[
            "a vast open steppe", "a mountain valley", "a yurt interior",
            "a riverbank", "a high mountain pass", "a forest clearing",
            "a lakeside at dawn", "a canyon with natural echo",
            "a herder's camp", "a festival ground",
        ],
        ensemble_contexts=[
            "a throat singing trio", "an igil and voice duo",
            "a jaw harp and voice duo", "a full folk ensemble",
            "a festival competition performance", "a solo throat singing recital",
            "a nature soundscape mimicry performance", "a bowed string ensemble",
            "a ceremonial drum and voice duo", "a family singing circle",
        ],
        blind_descriptors=[
            "deep fundamental drone with high whistling overtone melody above",
            "extremely low vocal frequency with rattling subharmonic undertone",
            "single voice producing two distinct simultaneous pitches",
            "bowed two-string fiddle in pentatonic melody over drone",
            "jaw harp buzzing with amplified overtone selection",
            "overtone melody tracing pentatonic scale over sustained fundamental",
            "breathy end-blown flute with wind-like tone quality",
            "plucked three-string lute in rhythmic accompaniment pattern",
            "rolling pulsating throat texture with rapid modulation",
            "frame drum providing steady pulse beneath throat singing",
            "nasal resonance creating distinct buzzing overtone quality",
            "voice imitating sound of flowing water",
            "voice imitating galloping horse rhythm",
            "high piercing whistle tone sustained over chest drone",
            "birch bark horn producing raw natural tone",
            "multiple overtone pitches shifting in melodic sequence",
            "bowed string and throat singing in parallel motion",
            "bells and rattles providing shamanic rhythmic texture",
            "button accordion providing harmonic accompaniment",
            "zither strings resonating sympathetically with voice",
            "deep growling voice transitioning to high whistle",
            "solo voice in vast reverberant natural space",
            "plucked lute rhythmic pattern mimicking horse trot",
            "throat singing with gradual dynamic crescendo",
            "metallic jaw harp with pitch bending technique",
            "vocal drone shifting fundamental pitch slowly",
            "voice and bowed string in heterophonic melody",
            "frame drum accelerating from slow ritual to fast dance",
            "overtone singing creating melody without changing vowel",
            "nature mimicry voice imitating bird calls",
            "deep subharmonic rumble beneath soft throat tone",
            "flute playing free-rhythm melody in open landscape",
            "solo voice with extreme resonance in natural echo",
            "hunting horn signal call across open terrain",
            "two throat singers in overlapping drone texture",
            "rhythmic rattle accompanying ceremonial chanting",
            "bowed fiddle tremolo creating sustained shimmering tone",
            "jaw harp melody synchronized with throat singing",
            "voice transitioning between four distinct timbral techniques",
            "quiet humming drone building to powerful overtone display",
            "plucked strings and voice mimicking wind patterns",
            "extremely sustained breath supporting long drone phrase",
            "metallic overtone series articulated by tongue position",
            "deep chest resonance amplified by throat constriction",
            "pastoral melody on bowed string with nature backdrop",
            "rhythmic breathing pattern creating percussive vocal effect",
            "echo of voice returning from distant cliff face",
            "gradual transition from speech to full overtone singing",
            "voice blending with natural environmental sounds",
            "final sustained overtone fading into landscape silence",
        ],
    ),

    # ── 13. Aboriginal Australian ─────────────────────────────────────────────
    TraditionSpec(
        name="Aboriginal Australian",
        region_labels=["Aboriginal Australian", "First Nations Australian", "Indigenous Australian"],
        instruments=[
            "didgeridoo (yidaki)", "clapsticks (bilma)", "bullroarer",
            "gum leaf", "skin drum", "boomerang clapsticks",
            "seed rattle", "hollow log drum (lorrkon)", "woomera (clap)",
            "stamping tubes", "rasp sticks", "shell rattle",
            "stone clap sticks", "bark trumpet", "bone clapper",
            "rhythm sticks (nulla nulla)", "paperbark rattle",
            "water drum", "thigh slap percussion", "ground stomp",
        ],
        vocal_styles=[
            "songline ceremonial singing", "corroboree performance chanting",
            "solo songman singing", "group ceremonial unison chanting",
            "mourning wailing song", "healing song singing",
            "children's play song", "hunting mimicry song",
            "dawn ceremony singing", "storytelling song cycle",
        ],
        spatial_contexts=[
            "a desert campfire circle", "a riverbed ceremony ground",
            "a rock shelter", "an open bushland clearing",
            "a coastal beach at dusk", "a sandstone gorge",
            "a eucalyptus woodland", "a waterhole gathering point",
            "a sacred ceremonial ground", "a night sky ceremony site",
        ],
        ensemble_contexts=[
            "a songman with clapstick accompaniment", "a didgeridoo and clapstick duo",
            "a ceremonial singing group", "a corroboree performance ensemble",
            "a women's singing group", "a dance ceremony group",
            "a solo didgeridoo performance", "a healing ceremony group",
            "a storytelling performance", "a children's song group",
        ],
        blind_descriptors=[
            "continuous circular-breathed drone with overtone manipulation",
            "paired hardwood sticks producing sharp rhythmic crack",
            "whirring roar from swung wooden blade cutting air",
            "leaf held to lips producing high-pitched buzzing melody",
            "deep resonant drum from struck hollow log",
            "vocal drone imitating buzzing of insects",
            "rhythmic foot stomping on hard earth surface",
            "seeds in container creating continuous shaking sound",
            "voice mimicking bird calls with accurate pitch",
            "low continuous drone with rhythmic pulsation from cheeks",
            "sharp wood-on-wood percussion in steady pattern",
            "voice and drone instrument in unison melodic contour",
            "group voices chanting in rhythmic syllabic pattern",
            "boomerang-shaped sticks clapped together rhythmically",
            "drone with vocal overtone yelps and animal calls",
            "bark instrument producing low natural resonant tone",
            "bone percussion creating dry clicking rhythm",
            "water splashing rhythmically as percussion instrument",
            "thigh slapping creating deep body percussion",
            "ground stomping feet creating earth-shaking pulse",
            "high wailing voice in ascending lament contour",
            "drone modulating between two fundamental pitches",
            "complex vocal rhythm mimicking animal movement",
            "resonant stone sticks producing bright pitched clicks",
            "shell rattles creating high-frequency rhythmic shimmer",
            "solo voice in vast open acoustic environment",
            "continuous drone evolving timbrally over minutes",
            "vocal yelp interrupting steady drone rhythm",
            "multiple clapstick pairs creating polyrhythmic texture",
            "deep growling drone with lip-technique variation",
            "night ceremony sounds mixing voice and percussion",
            "rasp sticks scraped in rhythmic pattern",
            "stamping tubes producing different pitched thumps",
            "paperbark rustling as rhythmic accompaniment",
            "healing ceremony vocal pattern with drone support",
            "mimicry of wind through landscape in vocal technique",
            "gradual acceleration of rhythmic clapstick pattern",
            "drone instrument responding to dancer's movements",
            "single voice tracing melodic contour of landscape",
            "group response repeating after solo singer's phrase",
            "dawn chorus blending human voice with natural sounds",
            "percussive vocal technique producing rhythmic clicks",
            "long sustained vocal note fading into drone",
            "rhythmic cycle repeating with subtle variations",
            "drone harmonics shifting in response to vocal melody",
            "environmental sounds integrated into musical performance",
            "ceremony ending with collective final vocal sound",
            "quiet rhythmic breathing as musical element",
            "drone fading as clapsticks slow to final beat",
            "vast silence surrounding isolated musical sounds",
        ],
    ),

    # ── 14. Flamenco / Andalusian ─────────────────────────────────────────────
    TraditionSpec(
        name="Flamenco",
        region_labels=["Flamenco", "Andalusian", "Flamenco traditional"],
        instruments=[
            "flamenco guitar", "cajón", "palmas (hand claps)",
            "castanets (castañuelas)", "taconeo (heel percussion)",
            "pandero (frame drum)", "bandurria", "laúd",
            "violin (flamenco)", "flute (flamenco)", "electric bass",
            "piano (flamenco)", "cello (flamenco nuevo)", "percussion kit",
            "harmonica", "saxophone (flamenco fusion)", "cajón flamenco",
            "zanfona (hurdy-gurdy)", "abanico (fan)", "botella (bottle percussion)",
        ],
        vocal_styles=[
            "cante jondo deep song", "cante chico light singing",
            "cante intermedio medium-form singing", "siguiriya intense lament",
            "soleá solemn verse singing", "bulerías festive rhythmic singing",
            "fandango lyrical singing", "tangos rhythmic singing",
            "martinete unaccompanied forge song", "saeta processional devotional singing",
        ],
        spatial_contexts=[
            "a tablao performance stage", "a cave venue (cueva)",
            "a courtyard (patio) at night", "a street procession",
            "a festival stage", "a flamenco peña (social club)",
            "a forge workshop", "a small bar interior",
            "a cathedral plaza during Holy Week", "an outdoor summer terrace",
        ],
        ensemble_contexts=[
            "a cuadro flamenco (guitar, voice, dance)", "a solo guitar recital",
            "a cantaor with guitar accompaniment", "a festive bulerías circle",
            "a percussion and palmas group", "a flamenco nuevo fusion ensemble",
            "an unaccompanied solo voice", "a guitar and cajón duo",
            "a dance performance ensemble", "a flamenco jazz crossover group",
        ],
        blind_descriptors=[
            "nylon-string guitar in rapid rasgueado strumming technique",
            "wooden box drum providing deep bass and snappy slap tones",
            "complex hand-clap patterns in interlocking rhythms",
            "heel stomping creating percussive rhythmic fury on wood floor",
            "castanets clicking in rapid continuous rhythmic roll",
            "raw powerful voice with emotional breaking quality",
            "guitar tremolo sustaining crying melodic line",
            "rhythmic shout (jaleo) punctuating between musical phrases",
            "solo voice wailing in descending melismatic phrase",
            "guitar picado playing rapid single-note melody",
            "percussive guitar technique knocking on body",
            "duende-filled voice cracking with emotional intensity",
            "twelve-beat rhythmic cycle with complex accent pattern",
            "guitar harmonics ringing bell-like at phrase endings",
            "dancer's feet creating intricate rhythmic patterns",
            "group palmas driving festive rhythmic energy",
            "unaccompanied voice in vast reverberant space",
            "guitar and voice in call-and-response dialogue",
            "gradual acceleration building dramatic tension",
            "sudden silence (corte) breaking rhythmic flow",
            "bass guitar providing deep groove foundation",
            "piano playing percussive rhythmic chords",
            "flute adding lyrical melody over compás rhythm",
            "frame drum providing soft underlying pulse",
            "fan snapping rhythm as percussive element",
            "bottle struck as pitched percussion",
            "guitar playing Phrygian cadence resolution",
            "voice holding long sustained note with vibrato",
            "multiple rhythmic layers creating dense compás texture",
            "guitar alzapúa thumb technique driving rhythm",
            "emotional vocal climax with maximum intensity",
            "quiet intimate guitar passage in free tempo",
            "rhythmic foot and hand percussion synchronized",
            "Moorish-influenced melodic ornaments on guitar",
            "deep guttural vocal entrance building from silence",
            "festive atmosphere with clapping and shouting",
            "melancholy guitar solo in minor mode",
            "cello adding sustaining foundation in nuevo style",
            "rapid alternation between strumming and plucking",
            "group vocal response to solo cantaor phrase",
            "percussive bodywork sounds of dancer mixed with music",
            "guitar playing falsetas melodic interludes",
            "voice with Arabic-influenced melismatic ornament",
            "cajón solo showcasing dynamic and timbral range",
            "hurdy-gurdy drone in experimental flamenco context",
            "saxophone weaving jazz-influenced lines over compás",
            "final dramatic remate ending with precise ensemble hit",
            "whispered vocal beginning building to powerful shout",
            "harmonica adding blues-inflected color to flamenco",
            "massive ensemble finale with stomping clapping and guitar",
        ],
    ),

    # ── 15. Electronic Club Music ─────────────────────────────────────────────
    TraditionSpec(
        name="Electronic",
        region_labels=["electronic", "electronic club", "electronic dance"],
        instruments=[
            "TR-808 drum machine", "TR-909 drum machine", "synthesizer",
            "sampler", "turntable", "drum pad controller",
            "modular synthesizer", "bass synthesizer", "vocoder",
            "sequencer", "effects processor", "laptop computer",
            "MIDI controller", "analog filter", "digital audio workstation",
            "granular synthesizer", "FM synthesizer", "wavetable synthesizer",
            "subtractive synthesizer", "eurorack module",
        ],
        vocal_styles=[
            "vocoded processed singing", "pitch-shifted vocal chops",
            "whispered ambient vocal texture", "spoken word sample",
            "auto-tuned melodic singing", "distorted screaming vocal",
            "dub echo vocal delay", "chopped and screwed vocal",
            "robotic text-to-speech", "time-stretched vocal drone",
        ],
        spatial_contexts=[
            "a dark underground club", "a warehouse rave",
            "a festival main stage", "a chill-out room",
            "a bedroom production studio", "a rooftop party at sunset",
            "a radio broadcast", "a headphone listening session",
            "an art installation space", "a car driving at night",
        ],
        ensemble_contexts=[
            "a DJ set with turntables", "a live electronic performance",
            "a modular synth improvisation", "a laptop and controller set",
            "a synth and drum machine duo", "a full electronic live band",
            "a sound system with MC", "a DJ and VJ collaboration",
            "a bedroom producer solo session", "a live coding performance",
        ],
        blind_descriptors=[
            "four-on-the-floor kick drum at 128 BPM steady pulse",
            "deep sub-bass sine wave oscillating beneath beat",
            "hi-hat pattern in continuous sixteenth-note rhythm",
            "synthesizer pad sustaining warm chord wash",
            "acid bassline with resonant filter sweep",
            "clap sample on every second and fourth beat",
            "arpeggiator running rapid synthesizer pattern",
            "vinyl crackle and turntable scratch texture",
            "sidechain compression creating pumping rhythmic effect",
            "reverb tail washing over sparse beat elements",
            "build-up with rising filter sweep and snare roll",
            "drop moment with maximum bass impact",
            "glitchy stuttering vocal sample repeating",
            "ambient pad creating wide atmospheric stereo field",
            "low-frequency oscillator modulating filter cutoff slowly",
            "breakbeat drum pattern with syncopated shuffled hits",
            "granular synthesis creating evolving textural cloud",
            "massive detuned supersaw chord stab",
            "delay feedback creating rhythmic echo pattern",
            "white noise sweep building tension",
            "FM synthesis metallic bell-like tone",
            "wobble bass with tempo-synced modulation",
            "tape-saturated drum loop with warm distortion",
            "minimal techno loop with subtle evolving changes",
            "dub echo with long feedback trail",
            "distorted industrial percussion hits",
            "chiptune square wave melody in retro style",
            "field recording layered beneath electronic beat",
            "pitch-bent synthesizer riser sweeping upward",
            "chopped vocal sample rearranged rhythmically",
            "modular synthesizer generating random melodic sequence",
            "deep house organ chord stab with reverb",
            "compressed drum bus creating punchy tight sound",
            "phaser effect sweeping across synthesizer pad",
            "ring-modulated metallic texture",
            "tempo change dropping from fast to half-time feel",
            "stereo panning automation moving sound across field",
            "layered synthesizer textures creating dense wall of sound",
            "silence gap creating tension before next section",
            "bit-crushed degraded lo-fi drum sound",
            "parallel processed drums with heavy compression",
            "frequency-modulated bass growl",
            "ethereal reverbed melody floating above driving beat",
            "polyrhythmic percussion pattern against straight kick",
            "analog warmth from tube-saturated signal chain",
            "staccato synthesizer stabs in rhythmic pattern",
            "long evolving ambient drone with slow modulation",
            "razor-sharp digital synthesis high-frequency lead",
            "subsonic bass rumble felt more than heard",
            "final reverb tail decaying into complete silence",
        ],
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# PILLAR 2: Material-Physical Vocabulary
# ═══════════════════════════════════════════════════════════════════════════════

EXCITATION_TYPES = {
    "struck": [
        "hammered metal plate", "struck wooden block", "hit drum skin",
        "tapped glass surface", "beaten stone slab", "slapped water surface",
        "knocked hollow tube", "pounded earth floor", "struck hanging bell",
        "hit ceramic bowl", "tapped metal pipe", "beaten bamboo tube",
        "hammered anvil", "struck crystal glass", "hit tin can",
        "knocked coconut shell", "pounded wooden table", "tapped clay pot",
        "struck metal rail", "beaten leather skin",
    ],
    "bowed": [
        "bowed metal rod", "bowed glass edge", "bowed saw blade",
        "bowed cello string", "bowed cymbal edge", "bowed wine glass rim",
        "bowed vibraphone bar", "bowed guitar string with ebow",
        "bowed metal sheet", "bowed crystal bowl",
        "bowed steel wire", "bowed wooden plank edge",
        "bowed aluminum tube", "bowed nylon string",
        "bowed brass plate", "bowed spring",
    ],
    "plucked": [
        "plucked steel string", "plucked rubber band", "plucked wire fence",
        "plucked nylon string", "plucked gut string", "plucked metal spring",
        "plucked harp string", "plucked jaw harp tongue",
        "plucked thumb piano tine", "plucked bass string",
        "plucked zither string", "plucked banjo string",
        "plucked ukulele string", "plucked sitar string with sympathetic resonance",
        "plucked koto string with bridge vibration",
    ],
    "blown": [
        "blown across bottle top", "blown through metal tube",
        "blown through wooden flute", "blown into conch shell",
        "blown through brass mouthpiece", "blown across grass blade",
        "blown into clay ocarina", "blown through bamboo pipe",
        "blown into animal horn", "blown through organ pipe",
        "blown through reed instrument", "blown across pan pipe",
        "blown into kazoo", "blown through didgeridoo with circular breath",
        "blown into whistle", "blown through harmonica reed",
    ],
    "electronic": [
        "oscillator producing pure sine wave", "square wave buzzing at low frequency",
        "sawtooth wave with rich harmonics", "noise generator creating white noise",
        "filtered electronic pulse", "frequency-modulated synthetic tone",
        "granular synthesis texture cloud", "ring-modulated metallic tone",
        "wavetable synthesis morphing timbre", "analog feedback loop squealing",
        "bit-crushed degraded digital signal", "phase-distorted waveform",
        "additive synthesis building timbre", "subtractive synthesis filtered sweep",
        "physical modeling synthesis of struck plate",
    ],
    "vocal": [
        "voice humming single pitch", "voice singing sustained vowel",
        "voice whispering sibilant consonant", "voice shouting with distortion",
        "voice clicking tongue rhythmically", "voice producing lip trill",
        "voice gargling with water", "voice whistling melodic phrase",
        "voice producing vocal fry creak", "voice singing falsetto high note",
        "voice producing nasal hum", "voice creating beatbox kick sound",
        "voice inhaling with raspy throat", "voice producing overtone whistle",
        "voice making popping bilabial sound",
    ],
}

MATERIALS = {
    "metal": [
        "ringing steel bell", "shimmering brass cymbal", "bright aluminum pan",
        "dull iron chain", "resonant copper bowl", "tinkling silver spoon",
        "deep bronze gong", "rattling tin cans", "vibrating metal spring",
        "grinding metal file",
    ],
    "wood": [
        "hollow wooden box knock", "dense hardwood block tap",
        "resonant wooden marimba bar", "thin wooden plank vibration",
        "bamboo tube resonance", "wooden claves clicking",
        "cedar plank being bowed", "driftwood struck together",
        "balsa wood light tap", "thick oak door knock",
    ],
    "skin": [
        "taut drum skin slap", "loose skin buzzing",
        "fingertip roll on skin head", "palm strike on large drum",
        "stick hit on snare drum skin", "brush sweep across drum head",
        "rim shot on tight drum skin", "muted hand on bass drum",
        "thumb roll on tambourine skin", "wet hand sliding on drum surface",
    ],
    "string": [
        "steel guitar string vibrating", "nylon classical string resonating",
        "gut string warm pluck", "wound bass string deep vibration",
        "piano wire struck by hammer", "harp string glissando",
        "rubber band twang", "fishing line taut vibration",
        "bowed cello string sustain", "mandolin string pair tremolo",
    ],
    "air": [
        "breath through narrow opening", "wind across bottle mouth",
        "air column resonating in pipe", "compressed air burst",
        "gentle breeze through leaves", "storm wind howling",
        "air escaping balloon", "whistle of air through crack",
        "bellows pumping air through reed", "pneumatic air release hiss",
    ],
    "water": [
        "dripping water into pool", "running stream over stones",
        "ocean wave breaking on shore", "rain hitting metal roof",
        "water boiling in kettle", "underwater bubbles rising",
        "waterfall cascade roar", "gentle fountain trickling",
        "splashing hand in water", "ice cracking on frozen lake",
    ],
    "stone": [
        "river stones clinking together", "heavy boulder thud on earth",
        "pebbles cascading down slope", "stone struck on stone",
        "slate tiles tapped rhythmically", "grinding stone on stone",
        "marble rolling on hard floor", "flint striking with spark",
        "gravel crunching underfoot", "stone chime ringing when struck",
    ],
    "glass": [
        "crystal wine glass ringing", "glass bottle struck with spoon",
        "window pane vibrating from bass", "glass beads rattling in jar",
        "broken glass tinkling to floor", "glass harmonica singing tone",
        "stained glass panel buzzing sympathetically", "glass rod tapped on edge",
        "thick glass jar deep resonance", "thin glass sheet bending vibration",
    ],
    "plastic": [
        "plastic bucket drum thud", "PVC pipe resonating when struck",
        "plastic wrap crinkling", "acrylic sheet vibrating",
        "plastic comb teeth plucked", "hollow plastic ball bouncing",
        "styrofoam rubbing squeak", "plastic bag rustling",
        "thick plastic tube bonging", "flexible plastic ruler twang",
    ],
    "digital": [
        "quantized bit-crushed noise", "aliased digital waveform",
        "sample rate reduction artifacts", "digital clipping distortion",
        "compressed audio pumping artifact", "digital noise floor hiss",
        "codec compression artifact", "buffer underrun glitch",
        "DAC conversion stepping noise", "digital feedback loop",
    ],
}

ENVIRONMENTS = {
    "close_dry": [
        "sound recorded inches from source in dead room",
        "intimate close-mic recording in anechoic chamber",
        "completely dry recording with no room reflections",
    ],
    "small_room": [
        "sound in small tiled bathroom with bright reflections",
        "recording in a bedroom with carpet and soft furnishings",
        "sound in a small wooden practice room",
    ],
    "concert_hall": [
        "sound reverberating in a large concert hall",
        "recording from the back of a symphonic auditorium",
        "sound on stage of a medium concert venue",
    ],
    "cathedral": [
        "sound echoing in a vast stone cathedral",
        "reverberant Gothic church interior with long decay",
        "huge sacred space with multiple reflection layers",
    ],
    "outdoor": [
        "sound in an open field with no reflections",
        "recording on a city rooftop with distant traffic",
        "sound on a hilltop with wind ambience",
    ],
    "underwater": [
        "muffled sound through water with low-pass character",
        "hydrophone recording of submerged sound source",
        "underwater acoustic with amplified low frequencies",
    ],
    "cave": [
        "sound in a deep cave with complex reflections",
        "dripping cave echo with long diffuse reverb tail",
        "underground cavern with multiple distinct echoes",
    ],
    "canyon": [
        "sound bouncing between canyon walls in distinct echoes",
        "call echoing across a wide rocky gorge",
        "sound in a narrow slot canyon with flutter echo",
    ],
}

TIME_PATTERNS = {
    "impulsive": [
        "single sharp transient attack with instant decay",
        "gunshot-like impulse in reverberant space",
        "short click followed by silence",
        "staccato percussion hit with no sustain",
        "snap of breaking twig in quiet forest",
    ],
    "sustained": [
        "continuous steady tone held without variation",
        "organ note sustaining indefinitely at constant volume",
        "bowed string maintaining constant pitch and dynamic",
        "engine running at constant RPM",
        "drone held for thirty seconds without change",
    ],
    "decaying": [
        "bell struck once ringing into gradual silence",
        "piano note fading from forte to nothing",
        "gong vibrating with slowly diminishing resonance",
        "reverb tail fading over several seconds",
        "plucked string vibrating into stillness",
    ],
    "evolving": [
        "slowly morphing synthesizer texture over minutes",
        "environmental soundscape gradually changing character",
        "sound source moving from close to far away",
        "timbre transforming continuously from bright to dark",
        "layered texture with elements fading in and out",
    ],
    "looping": [
        "short rhythmic pattern repeating exactly every two seconds",
        "ostinato figure cycling without variation",
        "drum loop repeating with mechanical precision",
        "tape loop with slightly degrading quality each cycle",
        "phrase repeating with subtle cumulative changes",
    ],
    "stochastic": [
        "random clicking events at unpredictable intervals",
        "rain-like irregular impacts on surface",
        "popcorn popping in random bursts",
        "scattered granular texture with no pattern",
        "static-like noise with random amplitude variations",
    ],
}

SPECTRAL_AXES = {
    "bright_dark": [
        "extremely bright sound with emphasized high frequencies",
        "moderately bright with some high-frequency presence",
        "neutral balanced frequency spectrum",
        "slightly dark sound with reduced treble",
        "very dark muffled sound with dominant low frequencies",
    ],
    "tonal_noisy": [
        "pure clear tonal pitch with no noise component",
        "mostly tonal with slight breath noise",
        "equal mix of pitched and noise elements",
        "mostly noise with hint of pitch center",
        "pure noise with no discernible pitch",
    ],
    "harmonic_inharmonic": [
        "perfectly harmonic overtone series from fundamental",
        "mostly harmonic with slight inharmonicity",
        "balanced mix of harmonic and inharmonic partials",
        "mostly inharmonic metallic overtone structure",
        "completely inharmonic clangorous complex tone",
    ],
    "narrow_broadband": [
        "extremely narrow-band single frequency sine tone",
        "narrow bandwidth centered on single pitch",
        "moderate bandwidth with several frequency components",
        "wide bandwidth spanning multiple octaves",
        "full broadband white noise spanning entire audible range",
    ],
}

DYNAMICS = [
    "barely audible whisper at the threshold of hearing",
    "very quiet pianissimo gentle sound",
    "soft piano level comfortable listening",
    "moderate mezzo-forte conversational level",
    "loud forte demanding attention",
    "very loud fortissimo powerful sound",
    "extremely loud bordering on painful threshold",
    "gradual crescendo from silence to maximum volume",
    "gradual decrescendo from loud to silence",
    "sudden sforzando accent erupting from quiet",
    "subito piano sudden drop from loud to quiet",
    "terraced dynamics jumping between fixed levels",
    "hairpin crescendo-decrescendo swell",
    "tremolo dynamic fluctuation at rapid rate",
    "breath-length dynamic phrases rising and falling",
]


# ═══════════════════════════════════════════════════════════════════════════════
# STRUCTURAL CONTROLS
# ═══════════════════════════════════════════════════════════════════════════════

BASELINE_PROMPTS = [
    "sound", "music", "noise", "audio", "silence", "quiet room",
    "a sound playing", "musical performance", "acoustic signal",
    "recording of sound", "ambient environment", "background noise",
    "tone", "note", "pitch", "rhythm", "melody", "harmony",
    "vibration", "resonance", "echo", "frequency", "waveform",
    "acoustic", "sonic", "auditory", "listening", "hearing",
    "loud sound", "quiet sound", "high sound", "low sound",
    "fast rhythm", "slow rhythm", "bright tone", "dark tone",
    "short sound", "long sound", "sharp attack", "smooth sustain",
    "sound in a room", "outdoor sound", "natural sound",
    "artificial sound", "musical instrument", "human voice",
    "environmental sound", "mechanical sound", "digital sound",
    "warm sound", "cold sound", "rough sound", "smooth sound",
    "dense sound", "sparse sound", "clear sound", "fuzzy sound",
    "open sound", "closed sound", "round sound", "thin sound",
    "deep sound", "shallow sound", "pure sound", "complex sound",
    "organic sound", "synthetic sound", "live sound", "recorded sound",
    "near sound", "distant sound", "moving sound", "static sound",
    "pulsing sound", "steady sound", "evolving sound", "decaying sound",
    "building sound", "fading sound", "emerging sound", "disappearing sound",
    "dry sound", "wet reverberant sound", "compressed sound",
    "expansive sound", "focused sound", "diffuse sound",
    "monophonic sound", "polyphonic sound", "textured sound",
    "clean sound", "distorted sound", "filtered sound", "unprocessed sound",
    "abstract sound", "concrete sound", "representational sound",
    "non-representational sound", "familiar sound", "unfamiliar sound",
    "pleasant sound", "unpleasant sound", "neutral sound", "interesting sound",
    "a single sustained note", "two notes alternating",
    "ascending scale", "descending scale", "random notes",
    "rhythmic pattern repeating", "continuous drone",
    "gradual transformation of timbre", "sudden change in sound",
    "layered sounds building up", "sounds fading away one by one",
]

ABSURD_PROMPTS = [
    "purple sound of mathematical equations dissolving",
    "the taste of a melody becoming rectangular",
    "triangular silence screaming in blue",
    "eleven-dimensional chord collapsing into flavor",
    "the weight of a frequency measured in colors",
    "backwards future sound of yesterday's tomorrow",
    "square root of a drum hit multiplied by green",
    "invisible thunder made of numbers and shame",
    "the sound of ideas forgetting themselves",
    "musical friction between two abstract concepts",
    "a chord progression made of liquid geometry",
    "the acoustic shadow of a thought never had",
    "synthesized embarrassment played through wooden equations",
    "the resonant frequency of a paradox",
    "sound of a color changing its mind",
    "harmonic series of a non-existent integer",
    "the echo of silence bouncing off nothing",
    "rhythm composed entirely of pauses between pauses",
    "melody written in the key of transparent",
    "bass note heavier than its own absence",
    "the timbre of a philosophical question mark",
    "frequency response of an imaginary friend",
    "acoustic portrait of the number zero",
    "sound of one hand clapping in four dimensions",
    "musical notation written in evaporating ink",
    "the overtone series of a logical fallacy",
    "rhythm section composed of frozen concepts",
    "the sound of a mirror reflecting another mirror",
    "harmonic distortion of pure emptiness",
    "the acoustic footprint of a hypothetical",
    "music composed for instruments that contradict themselves",
    "the reverberation time of a fleeting thought",
    "tempo measured in units of forgetting",
    "the frequency spectrum of absolute ambiguity",
    "pitch bend on a note that never started",
    "dynamics ranging from invisible to theoretical",
    "the resonance of a question without a question mark",
    "attack transient of a sound that never arrives",
    "sustain pedal held down on pure abstraction",
    "release envelope of a concept returning to noise",
    "the sound of meaning becoming meaningless",
    "acoustic interference pattern between real and imagined",
    "the sonic texture of a blank page",
    "music playing backwards through a one-way membrane",
    "the fundamental frequency of uncertainty itself",
    "waveform shaped like the concept of elsewhere",
    "audio recorded from inside a closed metaphor",
    "the stereo field of a single-point paradox",
    "mastering engineer processing raw philosophical doubt",
    "the final mix of a song composed of only rests",
]

MINIMAL_PAIR_SEEDS = [
    ("loud piano", "quiet piano"),
    ("bright trumpet", "dark trumpet"),
    ("fast drumming", "slow drumming"),
    ("high flute", "low flute"),
    ("sharp attack guitar", "smooth attack guitar"),
    ("dry violin recording", "reverberant violin recording"),
    ("solo cello", "cello ensemble"),
    ("acoustic guitar", "electric guitar"),
    ("male voice singing", "female voice singing"),
    ("major chord", "minor chord"),
    ("staccato notes", "legato notes"),
    ("harmonic tone", "noisy tone"),
    ("close microphone recording", "distant microphone recording"),
    ("clean signal", "distorted signal"),
    ("ascending melody", "descending melody"),
    ("simple rhythm", "complex rhythm"),
    ("narrow bandwidth tone", "wide bandwidth noise"),
    ("steady pitch", "vibrato pitch"),
    ("single instrument", "full orchestra"),
    ("sustained note", "short percussive hit"),
    ("natural acoustic sound", "synthesized electronic sound"),
    ("warm analog synthesizer", "cold digital synthesizer"),
    ("gentle whisper", "powerful shout"),
    ("rhythmic pulse", "free-flowing ambient"),
    ("compressed dynamic range", "wide dynamic range"),
    ("monophonic single voice", "polyphonic multiple voices"),
    ("familiar musical scale", "unfamiliar microtonal scale"),
    ("regular steady tempo", "irregular changing tempo"),
    ("tonal centered pitch", "atonal no pitch center"),
    ("sparse minimal texture", "dense layered texture"),
    ("short two-second sound", "long thirty-second sound"),
    ("indoor recording", "outdoor recording"),
    ("morning birdsong ambience", "evening cricket ambience"),
    ("wooden percussion hit", "metal percussion hit"),
    ("bowed string sustained", "plucked string decay"),
    ("human singing voice", "human speaking voice"),
    ("wind instrument melody", "string instrument melody"),
    ("deep bass frequency", "high treble frequency"),
    ("acoustic drum kit", "electronic drum machine"),
    ("live concert recording", "studio produced recording"),
    ("jazz saxophone solo", "classical saxophone solo"),
    ("folk guitar strumming", "flamenco guitar strumming"),
    ("choir singing hymn", "choir singing lullaby"),
    ("marching band parade", "marching band concert"),
    ("rain on window", "rain on leaves"),
    ("cat purring softly", "cat meowing loudly"),
    ("car engine idling", "car engine revving"),
    ("clock ticking slowly", "clock ticking quickly"),
    ("door closing gently", "door slamming shut"),
    ("footsteps on gravel", "footsteps on wooden floor"),
]

COMPOSITIONAL_TEMPLATES = [
    # Cross-pillar: Pillar 2 excitation × Pillar 1 tradition context
    "{excitation} in {tradition} ensemble context",
    "{tradition} musician playing {excitation}",
    # Cross-pillar: Pillar 2 material × Pillar 2 environment
    "{material} sound in {environment}",
    # Cross-pillar: Pillar 2 spectral × Pillar 2 dynamics
    "{spectral} sound with {dynamic} volume",
    # Multi-attribute combinations
    "{excitation} with {time_pattern} temporal structure",
    "{material} resonating in {environment} with {spectral} quality",
    "{tradition} instrument made of {material_name}",
    "{excitation} creating {time_pattern} pattern in {environment}",
]
